# Generated by Django 4.2.4 on 2024-07-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docpack',
            name='Consilium_to_Coordinator_delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docpack',
            name='Consilium_to_Coordinator_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docpack',
            name='Coordinator_to_TBCenter_delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docpack',
            name='Coordinator_to_TBCenter_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docpack',
            name='TBCenter_to_Consilium_delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docpack',
            name='TBCenter_to_Consilium_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
